#!/bin/sh
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds070381.fasta -out 070381.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds071107.fasta -out 071107.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds10101.fasta -out 10101.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds10102.fasta -out 10102.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds10104.fasta -out 10104.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds10105.fasta -out 10105.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds10109.fasta -out 10109.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds101A.fasta -out 101A.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds10212.fasta -out 10212.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds10217.fasta -out 10217.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds102A.fasta -out 102A.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds10641.fasta -out 10641.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds10646.fasta -out 10646.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds10650.fasta -out 10650.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds106A.fasta -out 106A.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds109A.fasta -out 109A.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds113A.fasta -out 113A.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds117A.fasta -out 117A.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds118A.fasta -out 118A.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds120320.fasta -out 120320.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds121VP.fasta -out 121VP.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds12327.fasta -out 12327.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds123VP.fasta -out 123VP.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds125VP.fasta -out 125VP.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds126VP.fasta -out 126VP.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds12768.fasta -out 12768.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds127VP.fasta -out 127VP.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds12801.fasta -out 12801.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds128VP.fasta -out 128VP.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds129VP.fasta -out 129VP.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds130651.fasta -out 130651.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13105.fasta -out 13105.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13106.fasta -out 13106.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13107.fasta -out 13107.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13108.fasta -out 13108.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds131098.fasta -out 131098.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13109.fasta -out 13109.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13110.fasta -out 13110.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds131VP.fasta -out 131VP.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13213.fasta -out 13213.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13216.fasta -out 13216.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13217.fasta -out 13217.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13219.fasta -out 13219.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds132VP.fasta -out 132VP.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13432.fasta -out 13432.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13433.fasta -out 13433.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13435.fasta -out 13435.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds134VP.fasta -out 134VP.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13545.fasta -out 13545.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13761.fasta -out 13761.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13872.fasta -out 13872.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13985.fasta -out 13985.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13986.fasta -out 13986.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds13988.fasta -out 13988.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds5A12.fasta -out 5A12.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds5A13.fasta -out 5A13.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds5A15.fasta -out 5A15.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds5A16.fasta -out 5A16.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds5A18.fasta -out 5A18.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds5A19.fasta -out 5A19.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds5A1.fasta -out 5A1.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds5A20.fasta -out 5A20.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds5A2.fasta -out 5A2.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds5A4.fasta -out 5A4.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds5A5.fasta -out 5A5.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds5A6.fasta -out 5A6.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds5A7.fasta -out 5A7.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds5A8.fasta -out 5A8.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds5A9.fasta -out 5A9.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffolds5D62.fasta -out 5D62.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsEF13212.fasta -out EF13212.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsEF13431.fasta -out EF13431.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsIV12.fasta -out IV12.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsIV18.fasta -out IV18.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsIV22.fasta -out IV22.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsIV23.fasta -out IV23.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsIV28.fasta -out IV28.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsIV30.fasta -out IV30.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV102.fasta -out TV102.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV103.fasta -out TV103.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV104.fasta -out TV104.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV105.fasta -out TV105.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV106.fasta -out TV106.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV10.fasta -out TV10.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV111.fasta -out TV111.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV112.fasta -out TV112.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV118.fasta -out TV118.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV121.fasta -out TV121.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV123.fasta -out TV123.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV125.fasta -out TV125.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV126.fasta -out TV126.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV12.fasta -out TV12.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV135.fasta -out TV135.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV137.fasta -out TV137.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV138.fasta -out TV138.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV139.fasta -out TV139.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV13.fasta -out TV13.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV147.fasta -out TV147.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV148.fasta -out TV148.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV14.fasta -out TV14.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV154.fasta -out TV154.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV15.fasta -out TV15.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV162.fasta -out TV162.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV163.fasta -out TV163.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV18.fasta -out TV18.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV19.fasta -out TV19.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV20.fasta -out TV20.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV21.fasta -out TV21.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV28.fasta -out TV28.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV29.fasta -out TV29.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV2.fasta -out TV2.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV30.fasta -out TV30.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV32.fasta -out TV32.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV33.fasta -out TV33.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV3.fasta -out TV3.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV41.fasta -out TV41.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV42.fasta -out TV42.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV43.fasta -out TV43.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV44.fasta -out TV44.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV45.fasta -out TV45.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV46.fasta -out TV46.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV47.fasta -out TV47.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV48.fasta -out TV48.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV49.fasta -out TV49.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV4.fasta -out TV4.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV52.fasta -out TV52.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV54.fasta -out TV54.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV55.fasta -out TV55.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV56.fasta -out TV56.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV57.fasta -out TV57.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV58.fasta -out TV58.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV5.fasta -out TV5.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV70.fasta -out TV70.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV71.fasta -out TV71.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV73.fasta -out TV73.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV75.fasta -out TV75.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV76.fasta -out TV76.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV77.fasta -out TV77.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV78.fasta -out TV78.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV7.fasta -out TV7.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV81.fasta -out TV81.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV82.fasta -out TV82.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV83.fasta -out TV83.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV92.fasta -out TV92.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV97.fasta -out TV97.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV98.fasta -out TV98.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsTV9.fasta -out TV9.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsVV10.fasta -out VV10.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsVV11.fasta -out VV11.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsVV14.fasta -out VV14.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsVV15.fasta -out VV15.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsVV5.fasta -out VV5.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsVV6.fasta -out VV6.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsVV8.fasta -out VV8.txt -outfmt 6
blastn -db BceComponents.fasta -query /SCRATCH/RO_PROJECT/prokkaoutput/scaffoldsVV9.fasta -out VV9.txt -outfmt 6
