#!/bin/sh
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds070381.fasta -out BLASTOUTPUT/070381.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds071107.fasta -out BLASTOUTPUT/071107.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds10101.fasta -out BLASTOUTPUT/10101.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds10102.fasta -out BLASTOUTPUT/10102.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds10104.fasta -out BLASTOUTPUT/10104.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds10105.fasta -out BLASTOUTPUT/10105.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds10109.fasta -out BLASTOUTPUT/10109.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds101A.fasta -out BLASTOUTPUT/101A.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds10212.fasta -out BLASTOUTPUT/10212.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds10217.fasta -out BLASTOUTPUT/10217.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds102A.fasta -out BLASTOUTPUT/102A.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds10641.fasta -out BLASTOUTPUT/10641.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds10646.fasta -out BLASTOUTPUT/10646.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds10650.fasta -out BLASTOUTPUT/10650.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds106A.fasta -out BLASTOUTPUT/106A.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds109A.fasta -out BLASTOUTPUT/109A.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds113A.fasta -out BLASTOUTPUT/113A.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds117A.fasta -out BLASTOUTPUT/117A.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds118A.fasta -out BLASTOUTPUT/118A.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds120320.fasta -out BLASTOUTPUT/120320.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds121VP.fasta -out BLASTOUTPUT/121VP.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds12327.fasta -out BLASTOUTPUT/12327.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds123VP.fasta -out BLASTOUTPUT/123VP.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds125VP.fasta -out BLASTOUTPUT/125VP.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds126VP.fasta -out BLASTOUTPUT/126VP.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds12768.fasta -out BLASTOUTPUT/12768.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds127VP.fasta -out BLASTOUTPUT/127VP.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds12801.fasta -out BLASTOUTPUT/12801.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds128VP.fasta -out BLASTOUTPUT/128VP.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds129VP.fasta -out BLASTOUTPUT/129VP.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds130651.fasta -out BLASTOUTPUT/130651.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13105.fasta -out BLASTOUTPUT/13105.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13106.fasta -out BLASTOUTPUT/13106.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13107.fasta -out BLASTOUTPUT/13107.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13108.fasta -out BLASTOUTPUT/13108.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds131096.fasta -out BLASTOUTPUT/131096.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds131098.fasta -out BLASTOUTPUT/131098.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13109.fasta -out BLASTOUTPUT/13109.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13110.fasta -out BLASTOUTPUT/13110.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds131VP.fasta -out BLASTOUTPUT/131VP.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13213.fasta -out BLASTOUTPUT/13213.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13216.fasta -out BLASTOUTPUT/13216.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13217.fasta -out BLASTOUTPUT/13217.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13219.fasta -out BLASTOUTPUT/13219.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds132VP.fasta -out BLASTOUTPUT/132VP.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13432.fasta -out BLASTOUTPUT/13432.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13433.fasta -out BLASTOUTPUT/13433.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13435.fasta -out BLASTOUTPUT/13435.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds134VP.fasta -out BLASTOUTPUT/134VP.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13545.fasta -out BLASTOUTPUT/13545.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13761.fasta -out BLASTOUTPUT/13761.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13872.fasta -out BLASTOUTPUT/13872.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13985.fasta -out BLASTOUTPUT/13985.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13986.fasta -out BLASTOUTPUT/13986.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds13988.fasta -out BLASTOUTPUT/13988.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds5A12.fasta -out BLASTOUTPUT/5A12.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds5A13.fasta -out BLASTOUTPUT/5A13.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds5A15.fasta -out BLASTOUTPUT/5A15.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds5A16.fasta -out BLASTOUTPUT/5A16.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds5A18.fasta -out BLASTOUTPUT/5A18.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds5A19.fasta -out BLASTOUTPUT/5A19.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds5A1.fasta -out BLASTOUTPUT/5A1.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds5A20.fasta -out BLASTOUTPUT/5A20.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds5A2.fasta -out BLASTOUTPUT/5A2.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds5A4.fasta -out BLASTOUTPUT/5A4.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds5A5.fasta -out BLASTOUTPUT/5A5.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds5A6.fasta -out BLASTOUTPUT/5A6.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds5A7.fasta -out BLASTOUTPUT/5A7.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds5A8.fasta -out BLASTOUTPUT/5A8.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds5A9.fasta -out BLASTOUTPUT/5A9.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffolds5D62.fasta -out BLASTOUTPUT/5D62.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsEF13212.fasta -out BLASTOUTPUT/EF13212.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsEF13431.fasta -out BLASTOUTPUT/EF13431.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsIV12.fasta -out BLASTOUTPUT/IV12.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsIV18.fasta -out BLASTOUTPUT/IV18.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsIV22.fasta -out BLASTOUTPUT/IV22.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsIV23.fasta -out BLASTOUTPUT/IV23.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsIV28.fasta -out BLASTOUTPUT/IV28.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsIV30.fasta -out BLASTOUTPUT/IV30.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV102.fasta -out BLASTOUTPUT/TV102.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV103.fasta -out BLASTOUTPUT/TV103.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV104.fasta -out BLASTOUTPUT/TV104.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV105.fasta -out BLASTOUTPUT/TV105.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV106.fasta -out BLASTOUTPUT/TV106.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV10.fasta -out BLASTOUTPUT/TV10.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV111.fasta -out BLASTOUTPUT/TV111.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV112.fasta -out BLASTOUTPUT/TV112.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV118.fasta -out BLASTOUTPUT/TV118.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV121.fasta -out BLASTOUTPUT/TV121.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV123.fasta -out BLASTOUTPUT/TV123.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV125.fasta -out BLASTOUTPUT/TV125.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV126.fasta -out BLASTOUTPUT/TV126.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV12.fasta -out BLASTOUTPUT/TV12.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV135.fasta -out BLASTOUTPUT/TV135.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV137.fasta -out BLASTOUTPUT/TV137.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV138.fasta -out BLASTOUTPUT/TV138.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV139.fasta -out BLASTOUTPUT/TV139.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV13.fasta -out BLASTOUTPUT/TV13.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV147.fasta -out BLASTOUTPUT/TV147.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV148.fasta -out BLASTOUTPUT/TV148.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV14.fasta -out BLASTOUTPUT/TV14.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV154.fasta -out BLASTOUTPUT/TV154.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV15.fasta -out BLASTOUTPUT/TV15.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV162.fasta -out BLASTOUTPUT/TV162.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV163.fasta -out BLASTOUTPUT/TV163.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV18.fasta -out BLASTOUTPUT/TV18.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV19.fasta -out BLASTOUTPUT/TV19.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV20.fasta -out BLASTOUTPUT/TV20.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV21.fasta -out BLASTOUTPUT/TV21.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV28.fasta -out BLASTOUTPUT/TV28.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV29.fasta -out BLASTOUTPUT/TV29.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV2.fasta -out BLASTOUTPUT/TV2.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV30.fasta -out BLASTOUTPUT/TV30.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV32.fasta -out BLASTOUTPUT/TV32.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV33.fasta -out BLASTOUTPUT/TV33.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV3.fasta -out BLASTOUTPUT/TV3.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV41.fasta -out BLASTOUTPUT/TV41.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV42.fasta -out BLASTOUTPUT/TV42.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV43.fasta -out BLASTOUTPUT/TV43.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV44.fasta -out BLASTOUTPUT/TV44.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV45.fasta -out BLASTOUTPUT/TV45.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV46.fasta -out BLASTOUTPUT/TV46.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV47.fasta -out BLASTOUTPUT/TV47.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV48.fasta -out BLASTOUTPUT/TV48.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV49.fasta -out BLASTOUTPUT/TV49.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV4.fasta -out BLASTOUTPUT/TV4.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV52.fasta -out BLASTOUTPUT/TV52.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV54.fasta -out BLASTOUTPUT/TV54.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV55.fasta -out BLASTOUTPUT/TV55.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV56.fasta -out BLASTOUTPUT/TV56.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV57.fasta -out BLASTOUTPUT/TV57.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV58.fasta -out BLASTOUTPUT/TV58.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV5.fasta -out BLASTOUTPUT/TV5.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV70.fasta -out BLASTOUTPUT/TV70.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV71.fasta -out BLASTOUTPUT/TV71.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV73.fasta -out BLASTOUTPUT/TV73.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV75.fasta -out BLASTOUTPUT/TV75.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV76.fasta -out BLASTOUTPUT/TV76.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV77.fasta -out BLASTOUTPUT/TV77.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV78.fasta -out BLASTOUTPUT/TV78.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV7.fasta -out BLASTOUTPUT/TV7.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV81.fasta -out BLASTOUTPUT/TV81.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV82.fasta -out BLASTOUTPUT/TV82.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV83.fasta -out BLASTOUTPUT/TV83.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV92.fasta -out BLASTOUTPUT/TV92.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV97.fasta -out BLASTOUTPUT/TV97.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV98.fasta -out BLASTOUTPUT/TV98.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsTV9.fasta -out BLASTOUTPUT/TV9.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsVV10.fasta -out BLASTOUTPUT/VV10.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsVV11.fasta -out BLASTOUTPUT/VV11.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsVV14.fasta -out BLASTOUTPUT/VV14.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsVV15.fasta -out BLASTOUTPUT/VV15.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsVV5.fasta -out BLASTOUTPUT/VV5.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsVV6.fasta -out BLASTOUTPUT/VV6.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsVV8.fasta -out BLASTOUTPUT/VV8.txt -outfmt 6
blastn -db nooperon_BcrRABD_fasta_format.fasta -query scaffoldsVV9.fasta -out BLASTOUTPUT/VV9.txt -outfmt 6
