#!/bin/sh
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds070381.fasta -out BLASTOUTPUTvanAermB/070381.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds071107.fasta -out BLASTOUTPUTvanAermB/071107.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds10101.fasta -out BLASTOUTPUTvanAermB/10101.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds10102.fasta -out BLASTOUTPUTvanAermB/10102.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds10104.fasta -out BLASTOUTPUTvanAermB/10104.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds10105.fasta -out BLASTOUTPUTvanAermB/10105.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds10109.fasta -out BLASTOUTPUTvanAermB/10109.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds101A.fasta -out BLASTOUTPUTvanAermB/101A.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds10212.fasta -out BLASTOUTPUTvanAermB/10212.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds10217.fasta -out BLASTOUTPUTvanAermB/10217.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds102A.fasta -out BLASTOUTPUTvanAermB/102A.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds10641.fasta -out BLASTOUTPUTvanAermB/10641.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds10646.fasta -out BLASTOUTPUTvanAermB/10646.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds10650.fasta -out BLASTOUTPUTvanAermB/10650.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds106A.fasta -out BLASTOUTPUTvanAermB/106A.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds109A.fasta -out BLASTOUTPUTvanAermB/109A.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds113A.fasta -out BLASTOUTPUTvanAermB/113A.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds117A.fasta -out BLASTOUTPUTvanAermB/117A.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds118A.fasta -out BLASTOUTPUTvanAermB/118A.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds120320.fasta -out BLASTOUTPUTvanAermB/120320.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds121VP.fasta -out BLASTOUTPUTvanAermB/121VP.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds12327.fasta -out BLASTOUTPUTvanAermB/12327.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds123VP.fasta -out BLASTOUTPUTvanAermB/123VP.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds125VP.fasta -out BLASTOUTPUTvanAermB/125VP.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds126VP.fasta -out BLASTOUTPUTvanAermB/126VP.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds12768.fasta -out BLASTOUTPUTvanAermB/12768.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds127VP.fasta -out BLASTOUTPUTvanAermB/127VP.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds12801.fasta -out BLASTOUTPUTvanAermB/12801.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds128VP.fasta -out BLASTOUTPUTvanAermB/128VP.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds129VP.fasta -out BLASTOUTPUTvanAermB/129VP.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds130651.fasta -out BLASTOUTPUTvanAermB/130651.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13105.fasta -out BLASTOUTPUTvanAermB/13105.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13106.fasta -out BLASTOUTPUTvanAermB/13106.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13107.fasta -out BLASTOUTPUTvanAermB/13107.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13108.fasta -out BLASTOUTPUTvanAermB/13108.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds131096.fasta -out BLASTOUTPUTvanAermB/131096.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds131098.fasta -out BLASTOUTPUTvanAermB/131098.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13109.fasta -out BLASTOUTPUTvanAermB/13109.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13110.fasta -out BLASTOUTPUTvanAermB/13110.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds131VP.fasta -out BLASTOUTPUTvanAermB/131VP.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13213.fasta -out BLASTOUTPUTvanAermB/13213.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13216.fasta -out BLASTOUTPUTvanAermB/13216.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13217.fasta -out BLASTOUTPUTvanAermB/13217.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13219.fasta -out BLASTOUTPUTvanAermB/13219.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds132VP.fasta -out BLASTOUTPUTvanAermB/132VP.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13432.fasta -out BLASTOUTPUTvanAermB/13432.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13433.fasta -out BLASTOUTPUTvanAermB/13433.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13435.fasta -out BLASTOUTPUTvanAermB/13435.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds134VP.fasta -out BLASTOUTPUTvanAermB/134VP.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13545.fasta -out BLASTOUTPUTvanAermB/13545.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13761.fasta -out BLASTOUTPUTvanAermB/13761.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13872.fasta -out BLASTOUTPUTvanAermB/13872.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13985.fasta -out BLASTOUTPUTvanAermB/13985.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13986.fasta -out BLASTOUTPUTvanAermB/13986.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds13988.fasta -out BLASTOUTPUTvanAermB/13988.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds5A12.fasta -out BLASTOUTPUTvanAermB/5A12.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds5A13.fasta -out BLASTOUTPUTvanAermB/5A13.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds5A15.fasta -out BLASTOUTPUTvanAermB/5A15.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds5A16.fasta -out BLASTOUTPUTvanAermB/5A16.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds5A18.fasta -out BLASTOUTPUTvanAermB/5A18.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds5A19.fasta -out BLASTOUTPUTvanAermB/5A19.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds5A1.fasta -out BLASTOUTPUTvanAermB/5A1.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds5A20.fasta -out BLASTOUTPUTvanAermB/5A20.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds5A2.fasta -out BLASTOUTPUTvanAermB/5A2.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds5A4.fasta -out BLASTOUTPUTvanAermB/5A4.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds5A5.fasta -out BLASTOUTPUTvanAermB/5A5.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds5A6.fasta -out BLASTOUTPUTvanAermB/5A6.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds5A7.fasta -out BLASTOUTPUTvanAermB/5A7.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds5A8.fasta -out BLASTOUTPUTvanAermB/5A8.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds5A9.fasta -out BLASTOUTPUTvanAermB/5A9.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffolds5D62.fasta -out BLASTOUTPUTvanAermB/5D62.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsEF13212.fasta -out BLASTOUTPUTvanAermB/EF13212.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsEF13431.fasta -out BLASTOUTPUTvanAermB/EF13431.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsIV12.fasta -out BLASTOUTPUTvanAermB/IV12.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsIV18.fasta -out BLASTOUTPUTvanAermB/IV18.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsIV22.fasta -out BLASTOUTPUTvanAermB/IV22.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsIV23.fasta -out BLASTOUTPUTvanAermB/IV23.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsIV28.fasta -out BLASTOUTPUTvanAermB/IV28.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsIV30.fasta -out BLASTOUTPUTvanAermB/IV30.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV102.fasta -out BLASTOUTPUTvanAermB/TV102.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV103.fasta -out BLASTOUTPUTvanAermB/TV103.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV104.fasta -out BLASTOUTPUTvanAermB/TV104.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV105.fasta -out BLASTOUTPUTvanAermB/TV105.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV106.fasta -out BLASTOUTPUTvanAermB/TV106.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV10.fasta -out BLASTOUTPUTvanAermB/TV10.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV111.fasta -out BLASTOUTPUTvanAermB/TV111.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV112.fasta -out BLASTOUTPUTvanAermB/TV112.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV118.fasta -out BLASTOUTPUTvanAermB/TV118.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV121.fasta -out BLASTOUTPUTvanAermB/TV121.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV123.fasta -out BLASTOUTPUTvanAermB/TV123.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV125.fasta -out BLASTOUTPUTvanAermB/TV125.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV126.fasta -out BLASTOUTPUTvanAermB/TV126.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV12.fasta -out BLASTOUTPUTvanAermB/TV12.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV135.fasta -out BLASTOUTPUTvanAermB/TV135.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV137.fasta -out BLASTOUTPUTvanAermB/TV137.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV138.fasta -out BLASTOUTPUTvanAermB/TV138.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV139.fasta -out BLASTOUTPUTvanAermB/TV139.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV13.fasta -out BLASTOUTPUTvanAermB/TV13.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV147.fasta -out BLASTOUTPUTvanAermB/TV147.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV148.fasta -out BLASTOUTPUTvanAermB/TV148.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV14.fasta -out BLASTOUTPUTvanAermB/TV14.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV154.fasta -out BLASTOUTPUTvanAermB/TV154.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV15.fasta -out BLASTOUTPUTvanAermB/TV15.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV162.fasta -out BLASTOUTPUTvanAermB/TV162.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV163.fasta -out BLASTOUTPUTvanAermB/TV163.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV18.fasta -out BLASTOUTPUTvanAermB/TV18.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV19.fasta -out BLASTOUTPUTvanAermB/TV19.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV20.fasta -out BLASTOUTPUTvanAermB/TV20.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV21.fasta -out BLASTOUTPUTvanAermB/TV21.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV28.fasta -out BLASTOUTPUTvanAermB/TV28.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV29.fasta -out BLASTOUTPUTvanAermB/TV29.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV2.fasta -out BLASTOUTPUTvanAermB/TV2.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV30.fasta -out BLASTOUTPUTvanAermB/TV30.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV32.fasta -out BLASTOUTPUTvanAermB/TV32.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV33.fasta -out BLASTOUTPUTvanAermB/TV33.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV3.fasta -out BLASTOUTPUTvanAermB/TV3.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV41.fasta -out BLASTOUTPUTvanAermB/TV41.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV42.fasta -out BLASTOUTPUTvanAermB/TV42.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV43.fasta -out BLASTOUTPUTvanAermB/TV43.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV44.fasta -out BLASTOUTPUTvanAermB/TV44.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV45.fasta -out BLASTOUTPUTvanAermB/TV45.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV46.fasta -out BLASTOUTPUTvanAermB/TV46.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV47.fasta -out BLASTOUTPUTvanAermB/TV47.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV48.fasta -out BLASTOUTPUTvanAermB/TV48.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV49.fasta -out BLASTOUTPUTvanAermB/TV49.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV4.fasta -out BLASTOUTPUTvanAermB/TV4.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV52.fasta -out BLASTOUTPUTvanAermB/TV52.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV54.fasta -out BLASTOUTPUTvanAermB/TV54.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV55.fasta -out BLASTOUTPUTvanAermB/TV55.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV56.fasta -out BLASTOUTPUTvanAermB/TV56.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV57.fasta -out BLASTOUTPUTvanAermB/TV57.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV58.fasta -out BLASTOUTPUTvanAermB/TV58.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV5.fasta -out BLASTOUTPUTvanAermB/TV5.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV70.fasta -out BLASTOUTPUTvanAermB/TV70.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV71.fasta -out BLASTOUTPUTvanAermB/TV71.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV73.fasta -out BLASTOUTPUTvanAermB/TV73.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV75.fasta -out BLASTOUTPUTvanAermB/TV75.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV76.fasta -out BLASTOUTPUTvanAermB/TV76.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV77.fasta -out BLASTOUTPUTvanAermB/TV77.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV78.fasta -out BLASTOUTPUTvanAermB/TV78.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV7.fasta -out BLASTOUTPUTvanAermB/TV7.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV81.fasta -out BLASTOUTPUTvanAermB/TV81.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV82.fasta -out BLASTOUTPUTvanAermB/TV82.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV83.fasta -out BLASTOUTPUTvanAermB/TV83.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV92.fasta -out BLASTOUTPUTvanAermB/TV92.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV97.fasta -out BLASTOUTPUTvanAermB/TV97.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV98.fasta -out BLASTOUTPUTvanAermB/TV98.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsTV9.fasta -out BLASTOUTPUTvanAermB/TV9.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsVV10.fasta -out BLASTOUTPUTvanAermB/VV10.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsVV11.fasta -out BLASTOUTPUTvanAermB/VV11.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsVV14.fasta -out BLASTOUTPUTvanAermB/VV14.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsVV15.fasta -out BLASTOUTPUTvanAermB/VV15.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsVV5.fasta -out BLASTOUTPUTvanAermB/VV5.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsVV6.fasta -out BLASTOUTPUTvanAermB/VV6.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsVV8.fasta -out BLASTOUTPUTvanAermB/VV8.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsVV9.fasta -out BLASTOUTPUTvanAermB/VV9.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsAR00128.fasta -out BLASTOUTPUTvanAermB/AR00128.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsAR0036.fasta -out BLASTOUTPUTvanAermB/AR0036.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsAR011155.fasta -out BLASTOUTPUTvanAermB/AR011155.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsAR01139.fasta -out BLASTOUTPUTvanAermB/AR01139.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsAR01215.fasta -out BLASTOUTPUTvanAermB/AR01215.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsAR01673.fasta -out BLASTOUTPUTvanAermB/AR01673.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsAR01802.fasta -out BLASTOUTPUTvanAermB/AR01802.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsAR01912.fasta -out BLASTOUTPUTvanAermB/AR01912.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsAR96360.fasta -out BLASTOUTPUTvanAermB/AR96360.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsAR98565.fasta -out BLASTOUTPUTvanAermB/AR98565.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsAR991024.fasta -out BLASTOUTPUTvanAermB/AR991024.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsAR991107.fasta -out BLASTOUTPUTvanAermB/AR991107.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsAR99190.fasta -out BLASTOUTPUTvanAermB/AR99190.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsAR9984.fasta -out BLASTOUTPUTvanAermB/AR9984.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL04446.fasta -out BLASTOUTPUTvanAermB/ARL04446.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL04506.fasta -out BLASTOUTPUTvanAermB/ARL04506.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL04840.fasta -out BLASTOUTPUTvanAermB/ARL04840.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL05425.fasta -out BLASTOUTPUTvanAermB/ARL05425.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL0567.fasta -out BLASTOUTPUTvanAermB/ARL0567.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL071139.fasta -out BLASTOUTPUTvanAermB/ARL071139.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL071163.fasta -out BLASTOUTPUTvanAermB/ARL071163.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL071166.fasta -out BLASTOUTPUTvanAermB/ARL071166.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL071169.fasta -out BLASTOUTPUTvanAermB/ARL071169.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL071195.fasta -out BLASTOUTPUTvanAermB/ARL071195.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL071198.fasta -out BLASTOUTPUTvanAermB/ARL071198.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL071205.fasta -out BLASTOUTPUTvanAermB/ARL071205.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL071286.fasta -out BLASTOUTPUTvanAermB/ARL071286.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL071300.fasta -out BLASTOUTPUTvanAermB/ARL071300.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL071328.fasta -out BLASTOUTPUTvanAermB/ARL071328.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL071345.fasta -out BLASTOUTPUTvanAermB/ARL071345.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL071348.fasta -out BLASTOUTPUTvanAermB/ARL071348.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL071351.fasta -out BLASTOUTPUTvanAermB/ARL071351.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL071384.fasta -out BLASTOUTPUTvanAermB/ARL071384.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL07973.fasta -out BLASTOUTPUTvanAermB/ARL07973.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL08105.fasta -out BLASTOUTPUTvanAermB/ARL08105.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL081074.fasta -out BLASTOUTPUTvanAermB/ARL081074.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL081077.fasta -out BLASTOUTPUTvanAermB/ARL081077.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL081189.fasta -out BLASTOUTPUTvanAermB/ARL081189.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL081215.fasta -out BLASTOUTPUTvanAermB/ARL081215.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL081218.fasta -out BLASTOUTPUTvanAermB/ARL081218.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL081249.fasta -out BLASTOUTPUTvanAermB/ARL081249.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL081256.fasta -out BLASTOUTPUTvanAermB/ARL081256.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL081292.fasta -out BLASTOUTPUTvanAermB/ARL081292.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL081309.fasta -out BLASTOUTPUTvanAermB/ARL081309.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL081412.fasta -out BLASTOUTPUTvanAermB/ARL081412.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL081437.fasta -out BLASTOUTPUTvanAermB/ARL081437.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL08192.fasta -out BLASTOUTPUTvanAermB/ARL08192.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL08288.fasta -out BLASTOUTPUTvanAermB/ARL08288.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL0832.fasta -out BLASTOUTPUTvanAermB/ARL0832.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL08339.fasta -out BLASTOUTPUTvanAermB/ARL08339.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL0835.fasta -out BLASTOUTPUTvanAermB/ARL0835.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL08391.fasta -out BLASTOUTPUTvanAermB/ARL08391.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL08394.fasta -out BLASTOUTPUTvanAermB/ARL08394.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL0839.fasta -out BLASTOUTPUTvanAermB/ARL0839.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL08428.fasta -out BLASTOUTPUTvanAermB/ARL08428.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL0843.fasta -out BLASTOUTPUTvanAermB/ARL0843.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL0846.fasta -out BLASTOUTPUTvanAermB/ARL0846.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL08477.fasta -out BLASTOUTPUTvanAermB/ARL08477.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL08484.fasta -out BLASTOUTPUTvanAermB/ARL08484.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL08552.fasta -out BLASTOUTPUTvanAermB/ARL08552.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL0867.fasta -out BLASTOUTPUTvanAermB/ARL0867.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL08712.fasta -out BLASTOUTPUTvanAermB/ARL08712.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL08781.fasta -out BLASTOUTPUTvanAermB/ARL08781.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL08804.fasta -out BLASTOUTPUTvanAermB/ARL08804.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL08902.fasta -out BLASTOUTPUTvanAermB/ARL08902.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL08983.fasta -out BLASTOUTPUTvanAermB/ARL08983.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL09100.fasta -out BLASTOUTPUTvanAermB/ARL09100.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL091074a.fasta -out BLASTOUTPUTvanAermB/ARL091074a.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL091209.fasta -out BLASTOUTPUTvanAermB/ARL091209.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL091265.fasta -out BLASTOUTPUTvanAermB/ARL091265.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL091374.fasta -out BLASTOUTPUTvanAermB/ARL091374.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL09146.fasta -out BLASTOUTPUTvanAermB/ARL09146.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL09193.fasta -out BLASTOUTPUTvanAermB/ARL09193.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL09409.fasta -out BLASTOUTPUTvanAermB/ARL09409.txt -outfmt 6
blastn -db tetML_and_bcrABRDoperon.fasta -query /SCRATCH/RO_PROJECT/ALL_GENOME_FASTA/scaffoldsARL09542.fasta -out BLASTOUTPUTvanAermB/ARL09542.txt -outfmt 6
