#!/bin/sh
blastn -db qacC.fa -query scaffolds070381.fasta -out qacC_BLAST/070381.txt -outfmt 6
blastn -db qacC.fa -query scaffolds071107.fasta -out qacC_BLAST/071107.txt -outfmt 6
blastn -db qacC.fa -query scaffolds10101.fasta -out qacC_BLAST/10101.txt -outfmt 6
blastn -db qacC.fa -query scaffolds10102.fasta -out qacC_BLAST/10102.txt -outfmt 6
blastn -db qacC.fa -query scaffolds10104.fasta -out qacC_BLAST/10104.txt -outfmt 6
blastn -db qacC.fa -query scaffolds10105.fasta -out qacC_BLAST/10105.txt -outfmt 6
blastn -db qacC.fa -query scaffolds10109.fasta -out qacC_BLAST/10109.txt -outfmt 6
blastn -db qacC.fa -query scaffolds101A.fasta -out qacC_BLAST/101A.txt -outfmt 6
blastn -db qacC.fa -query scaffolds10212.fasta -out qacC_BLAST/10212.txt -outfmt 6
blastn -db qacC.fa -query scaffolds10217.fasta -out qacC_BLAST/10217.txt -outfmt 6
blastn -db qacC.fa -query scaffolds102A.fasta -out qacC_BLAST/102A.txt -outfmt 6
blastn -db qacC.fa -query scaffolds10641.fasta -out qacC_BLAST/10641.txt -outfmt 6
blastn -db qacC.fa -query scaffolds10646.fasta -out qacC_BLAST/10646.txt -outfmt 6
blastn -db qacC.fa -query scaffolds10650.fasta -out qacC_BLAST/10650.txt -outfmt 6
blastn -db qacC.fa -query scaffolds106A.fasta -out qacC_BLAST/106A.txt -outfmt 6
blastn -db qacC.fa -query scaffolds109A.fasta -out qacC_BLAST/109A.txt -outfmt 6
blastn -db qacC.fa -query scaffolds113A.fasta -out qacC_BLAST/113A.txt -outfmt 6
blastn -db qacC.fa -query scaffolds117A.fasta -out qacC_BLAST/117A.txt -outfmt 6
blastn -db qacC.fa -query scaffolds118A.fasta -out qacC_BLAST/118A.txt -outfmt 6
blastn -db qacC.fa -query scaffolds120320.fasta -out qacC_BLAST/120320.txt -outfmt 6
blastn -db qacC.fa -query scaffolds121VP.fasta -out qacC_BLAST/121VP.txt -outfmt 6
blastn -db qacC.fa -query scaffolds12327.fasta -out qacC_BLAST/12327.txt -outfmt 6
blastn -db qacC.fa -query scaffolds123VP.fasta -out qacC_BLAST/123VP.txt -outfmt 6
blastn -db qacC.fa -query scaffolds125VP.fasta -out qacC_BLAST/125VP.txt -outfmt 6
blastn -db qacC.fa -query scaffolds126VP.fasta -out qacC_BLAST/126VP.txt -outfmt 6
blastn -db qacC.fa -query scaffolds12768.fasta -out qacC_BLAST/12768.txt -outfmt 6
blastn -db qacC.fa -query scaffolds127VP.fasta -out qacC_BLAST/127VP.txt -outfmt 6
blastn -db qacC.fa -query scaffolds12801.fasta -out qacC_BLAST/12801.txt -outfmt 6
blastn -db qacC.fa -query scaffolds128VP.fasta -out qacC_BLAST/128VP.txt -outfmt 6
blastn -db qacC.fa -query scaffolds129VP.fasta -out qacC_BLAST/129VP.txt -outfmt 6
blastn -db qacC.fa -query scaffolds130651.fasta -out qacC_BLAST/130651.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13105.fasta -out qacC_BLAST/13105.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13106.fasta -out qacC_BLAST/13106.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13107.fasta -out qacC_BLAST/13107.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13108.fasta -out qacC_BLAST/13108.txt -outfmt 6
blastn -db qacC.fa -query scaffolds131096.fasta -out qacC_BLAST/131096.txt -outfmt 6
blastn -db qacC.fa -query scaffolds131098.fasta -out qacC_BLAST/131098.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13109.fasta -out qacC_BLAST/13109.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13110.fasta -out qacC_BLAST/13110.txt -outfmt 6
blastn -db qacC.fa -query scaffolds131VP.fasta -out qacC_BLAST/131VP.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13213.fasta -out qacC_BLAST/13213.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13216.fasta -out qacC_BLAST/13216.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13217.fasta -out qacC_BLAST/13217.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13219.fasta -out qacC_BLAST/13219.txt -outfmt 6
blastn -db qacC.fa -query scaffolds132VP.fasta -out qacC_BLAST/132VP.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13432.fasta -out qacC_BLAST/13432.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13433.fasta -out qacC_BLAST/13433.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13435.fasta -out qacC_BLAST/13435.txt -outfmt 6
blastn -db qacC.fa -query scaffolds134VP.fasta -out qacC_BLAST/134VP.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13545.fasta -out qacC_BLAST/13545.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13761.fasta -out qacC_BLAST/13761.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13872.fasta -out qacC_BLAST/13872.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13985.fasta -out qacC_BLAST/13985.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13986.fasta -out qacC_BLAST/13986.txt -outfmt 6
blastn -db qacC.fa -query scaffolds13988.fasta -out qacC_BLAST/13988.txt -outfmt 6
blastn -db qacC.fa -query scaffolds5A12.fasta -out qacC_BLAST/5A12.txt -outfmt 6
blastn -db qacC.fa -query scaffolds5A13.fasta -out qacC_BLAST/5A13.txt -outfmt 6
blastn -db qacC.fa -query scaffolds5A15.fasta -out qacC_BLAST/5A15.txt -outfmt 6
blastn -db qacC.fa -query scaffolds5A16.fasta -out qacC_BLAST/5A16.txt -outfmt 6
blastn -db qacC.fa -query scaffolds5A18.fasta -out qacC_BLAST/5A18.txt -outfmt 6
blastn -db qacC.fa -query scaffolds5A19.fasta -out qacC_BLAST/5A19.txt -outfmt 6
blastn -db qacC.fa -query scaffolds5A1.fasta -out qacC_BLAST/5A1.txt -outfmt 6
blastn -db qacC.fa -query scaffolds5A20.fasta -out qacC_BLAST/5A20.txt -outfmt 6
blastn -db qacC.fa -query scaffolds5A2.fasta -out qacC_BLAST/5A2.txt -outfmt 6
blastn -db qacC.fa -query scaffolds5A4.fasta -out qacC_BLAST/5A4.txt -outfmt 6
blastn -db qacC.fa -query scaffolds5A5.fasta -out qacC_BLAST/5A5.txt -outfmt 6
blastn -db qacC.fa -query scaffolds5A6.fasta -out qacC_BLAST/5A6.txt -outfmt 6
blastn -db qacC.fa -query scaffolds5A7.fasta -out qacC_BLAST/5A7.txt -outfmt 6
blastn -db qacC.fa -query scaffolds5A8.fasta -out qacC_BLAST/5A8.txt -outfmt 6
blastn -db qacC.fa -query scaffolds5A9.fasta -out qacC_BLAST/5A9.txt -outfmt 6
blastn -db qacC.fa -query scaffolds5D62.fasta -out qacC_BLAST/5D62.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsEF13212.fasta -out qacC_BLAST/EF13212.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsEF13431.fasta -out qacC_BLAST/EF13431.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsIV12.fasta -out qacC_BLAST/IV12.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsIV18.fasta -out qacC_BLAST/IV18.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsIV22.fasta -out qacC_BLAST/IV22.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsIV23.fasta -out qacC_BLAST/IV23.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsIV28.fasta -out qacC_BLAST/IV28.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsIV30.fasta -out qacC_BLAST/IV30.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV102.fasta -out qacC_BLAST/TV102.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV103.fasta -out qacC_BLAST/TV103.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV104.fasta -out qacC_BLAST/TV104.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV105.fasta -out qacC_BLAST/TV105.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV106.fasta -out qacC_BLAST/TV106.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV10.fasta -out qacC_BLAST/TV10.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV111.fasta -out qacC_BLAST/TV111.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV112.fasta -out qacC_BLAST/TV112.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV118.fasta -out qacC_BLAST/TV118.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV121.fasta -out qacC_BLAST/TV121.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV123.fasta -out qacC_BLAST/TV123.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV125.fasta -out qacC_BLAST/TV125.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV126.fasta -out qacC_BLAST/TV126.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV12.fasta -out qacC_BLAST/TV12.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV135.fasta -out qacC_BLAST/TV135.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV137.fasta -out qacC_BLAST/TV137.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV138.fasta -out qacC_BLAST/TV138.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV139.fasta -out qacC_BLAST/TV139.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV13.fasta -out qacC_BLAST/TV13.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV147.fasta -out qacC_BLAST/TV147.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV148.fasta -out qacC_BLAST/TV148.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV14.fasta -out qacC_BLAST/TV14.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV154.fasta -out qacC_BLAST/TV154.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV15.fasta -out qacC_BLAST/TV15.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV162.fasta -out qacC_BLAST/TV162.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV163.fasta -out qacC_BLAST/TV163.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV18.fasta -out qacC_BLAST/TV18.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV19.fasta -out qacC_BLAST/TV19.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV20.fasta -out qacC_BLAST/TV20.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV21.fasta -out qacC_BLAST/TV21.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV28.fasta -out qacC_BLAST/TV28.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV29.fasta -out qacC_BLAST/TV29.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV2.fasta -out qacC_BLAST/TV2.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV30.fasta -out qacC_BLAST/TV30.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV32.fasta -out qacC_BLAST/TV32.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV33.fasta -out qacC_BLAST/TV33.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV3.fasta -out qacC_BLAST/TV3.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV41.fasta -out qacC_BLAST/TV41.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV42.fasta -out qacC_BLAST/TV42.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV43.fasta -out qacC_BLAST/TV43.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV44.fasta -out qacC_BLAST/TV44.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV45.fasta -out qacC_BLAST/TV45.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV46.fasta -out qacC_BLAST/TV46.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV47.fasta -out qacC_BLAST/TV47.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV48.fasta -out qacC_BLAST/TV48.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV49.fasta -out qacC_BLAST/TV49.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV4.fasta -out qacC_BLAST/TV4.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV52.fasta -out qacC_BLAST/TV52.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV54.fasta -out qacC_BLAST/TV54.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV55.fasta -out qacC_BLAST/TV55.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV56.fasta -out qacC_BLAST/TV56.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV57.fasta -out qacC_BLAST/TV57.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV58.fasta -out qacC_BLAST/TV58.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV5.fasta -out qacC_BLAST/TV5.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV70.fasta -out qacC_BLAST/TV70.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV71.fasta -out qacC_BLAST/TV71.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV73.fasta -out qacC_BLAST/TV73.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV75.fasta -out qacC_BLAST/TV75.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV76.fasta -out qacC_BLAST/TV76.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV77.fasta -out qacC_BLAST/TV77.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV78.fasta -out qacC_BLAST/TV78.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV7.fasta -out qacC_BLAST/TV7.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV81.fasta -out qacC_BLAST/TV81.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV82.fasta -out qacC_BLAST/TV82.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV83.fasta -out qacC_BLAST/TV83.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV92.fasta -out qacC_BLAST/TV92.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV97.fasta -out qacC_BLAST/TV97.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV98.fasta -out qacC_BLAST/TV98.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsTV9.fasta -out qacC_BLAST/TV9.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsVV10.fasta -out qacC_BLAST/VV10.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsVV11.fasta -out qacC_BLAST/VV11.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsVV14.fasta -out qacC_BLAST/VV14.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsVV15.fasta -out qacC_BLAST/VV15.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsVV5.fasta -out qacC_BLAST/VV5.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsVV6.fasta -out qacC_BLAST/VV6.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsVV8.fasta -out qacC_BLAST/VV8.txt -outfmt 6
blastn -db qacC.fa -query scaffoldsVV9.fasta -out qacC_BLAST/VV9.txt -outfmt 6
